Create Table: CREATE TABLE `user_backup` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `bk_id` varchar(36) NOT NULL,
  `inst_ip` varchar(100) DEFAULT NULL,
  `inst_port` varchar(10) NOT NULL,
  `bk_server` varchar(15) NOT NULL,
  `start_time` datetime NOT NULL,
  `end_time` datetime NOT NULL,
  `elapsed_time` int(11) NOT NULL,
  `backuped_db` varchar(2048) DEFAULT NULL,
  `is_complete` varchar(200) DEFAULT NULL,
  `bk_size` varchar(10) NOT NULL,
  `bk_dir` varchar(200) NOT NULL,
  `transfer_start` datetime DEFAULT NULL,
  `transfer_end` datetime DEFAULT NULL,
  `transfer_elapsed` int(11) DEFAULT NULL,
  `transfer_complete` varchar(20) NOT NULL,
  `remote_dest` varchar(200) NOT NULL,
  `master_status` varchar(500) NOT NULL,
  `slave_status` varchar(500) NOT NULL,
  `tool_version` varchar(200) NOT NULL,
  `server_version` varchar(200) NOT NULL,
  `pybackup_version` varchar(200) DEFAULT NULL,
  `bk_command` varchar(2048) DEFAULT NULL,
  `tag` varchar(200) NOT NULL DEFAULT 'N/A',
  `is_deleted` char(1) NOT NULL DEFAULT 'N',
  `is_local_deleted` char(1) NOT NULL DEFAULT 'N',
  `is_remote_deleted` char(1) NOT NULL DEFAULT 'N',
  `local_delete_time` datetime DEFAULT NULL,
  `remote_delete_time` datetime DEFAULT NULL,
  `validate_status` varchar(20) NOT NULL DEFAULT 'N/A',
  PRIMARY KEY (`id`),
  UNIQUE KEY `bk_id` (`bk_id`),
  KEY `idx_start_time` (`start_time`),
  KEY `idx_transfer_start` (`transfer_start`)
) ENGINE=InnoDB AUTO_INCREMENT=41448 DEFAULT CHARSET=utf8
